contest/urls.py
from django.views.i18n import JavaScriptCatalog
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path


from contest import views as v

urlpatterns = i18n_patterns(
    path(
        "jsi18n/",
        JavaScriptCatalog.as_view(),
        name="javascript-catalog",
    ),
    path("admin/", admin.site.urls),
    path("", v.index),
    path("voting/", include("voting.urls", namespace="voting")),
)

voting/urls.py
from django.urls import path
from voting import views as v

app_name = "voting"
urlpatterns = [
    path("", v.participants, name="participants"),
    path("vote/", v.vote, name="vote"),
]

voting/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _


class Participant(models.Model):
    name = models.CharField(
        _("nome"), null=False, blank=False, max_length=255, unique=True
    )
    description = models.TextField(_("descrição"), null=True, blank=True)
    video_url = models.URLField(_("URL do vídeo"), null=False, blank=False)
    start_date = models.DateTimeField(_("início"), default=now)
    end_date = models.DateTimeField(_("término"))
    created_date = models.DateTimeField(_("created date"), auto_now_add=True)

    @property
    def votes(self):
        return Vote.objects.filter(participant=self).count()

    class Meta:
        verbose_name = _("participante")
        verbose_name_plural = _("participantes")

    def __str__(self):
        return self.name


class Vote(models.Model):
    cookie = models.TextField(unique=True)
    ip_address = models.GenericIPAddressField()
    participant = models.ForeignKey(Participant, on_delete=models.CASCADE, null=False)
    created_date = models.DateTimeField(
        _("created date"), auto_now_add=True, editable=False
    )

    class Meta:
        verbose_name = _("voto")
        verbose_name_plural = _("votos")


def check_vote(sender, instance, *args, **kwargs):
    count_ip = (
        Vote.objects.filter(ip_address=instance.ip_address)
        .exclude(cookie=instance.cookie)
        .count()
    )
    max_count_ip = 5
    if count_ip >= max_count_ip:
        raise ValueError(
            _(
                f"""Só é possível votar no mesmo participante {max_count_ip} vezes por uma mesma rede.
                Conecte-se a outra rede ou aguarde algumas horas e tente novamente."""
            )
        )

    if instance.participant.start_date >= now():
        raise ValueError(_("Votação ainda não foi aberta."))

    if instance.participant.end_date <= now():
        raise ValueError(_("Votação já foi finalizada."))


def check_dates(sender, instance, *args, **kwargs):
    if instance.start_date > instance.end_date:
        raise ValueError(_("Data de término deve ser maior que a data de início."))


pre_save.connect(check_vote, sender=Vote)
pre_save.connect(check_dates, sender=Participant)

contest/views.py
from django.shortcuts import redirect, render


def index(request):
    return redirect("/voting/", permanent=True)

voting/views.py
import secrets
import requests
from datetime import timedelta

from django.contrib import messages
from django.shortcuts import render
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from voting.models import Participant, Vote


def participants(request):
    context = {}

    context["participants"] = Participant.objects.all()

    response = render(request, "vote/participants.html", context=context)

    if not "uuid" in request.COOKIES:
        uuid = secrets.token_urlsafe(24)
        response.set_cookie(key="uuid", value=uuid, expires=now() + timedelta(days=30))

    return response


def vote(request):
    if request.method == "POST":
        r = requests.post(
            "https://www.google.com/recaptcha/api/siteverify",
            data={
                "secret": "6LeO5MYgAAAAAPqFyh-CdyJ4mIVLA5E-SqqPLqAG",
                "response": request.POST.get("g-recaptcha-response"),
            },
        )

        if not r.json().get("success"):
            messages.error(
                request,
                _("Captcha inválido."),
            )
            return participants(request)

        ip_address = request.META.get("HTTP_X_FORWARDED_FOR") or request.META.get(
            "REMOTE_ADDR"
        )

        if not "uuid" in request.COOKIES or not ip_address:
            messages.error(
                request,
                _(
                    "Não foi possível salvar seu voto. Verifique se o seu navegador não está em modo anônimo e se os cookies estão habilitados."
                ),
            )
            return participants(request)

        try:
            vote, created = Vote.objects.update_or_create(
                cookie=request.COOKIES.get("uuid"),
                defaults={
                    "participant_id": request.POST.get("participant-id"),
                    "ip_address": ip_address,
                },
            )

            if created:
                messages.success(
                    request,
                    _("Voto salvo com sucesso."),
                )
            else:
                messages.success(
                    request,
                    _("Voto alterado com sucesso."),
                )

        except ValueError as e:
            messages.error(request, e)

    return participants(request)

contest/templates/contest/base.html
{% load static %}
{% load i18n %}

<html>
    <head>
        <title>_zine vs zine</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/gh/Joe12387/detectIncognito@main/detectIncognito.min.js"></script>
        <script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback" async defer></script>
        <link rel="shortcut icon" type="image/png" href="{% static "contest/images/favicon.png" %}" />
        <link href="{% static "contest/css/base.css" %}" rel="stylesheet" />
        <script src="{% url "javascript-catalog" %}"></script>
        <script>
            var static_url = "{% get_static_prefix %}";
            var media_url = "{% get_media_prefix %}";
        </script>
        <script type="text/javascript" src="{% static "contest/js/base.js" %}"></script>
        
        {% block head %}
        {% endblock head %}
    </head>
    <body>
        <div id="header">
            <a href="https://festivalimaginaria.com.br/" target="_blank">
                <img id="logo" src="{% static 'contest/images/imaginaria.png' %}"/>
            </a>
            <img id="contest" src="{% static 'contest/images/zine_vs_zine.png' %}"/>
            {% comment %} <h1>_zine vs zine</h1> {% endcomment %}
        </div>
        
        {% include "contest/messages.html" %}
        
        <div id="content">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

contest/templates/contest/messages.html
{% if messages or form.errors %}
  <ul class="messages">
    {% for message in messages %}
      <li onclick="this.remove()" {% if message.tags %}class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}

voting/templates/vote/_participant.html
{% load static %} {% load i18n %}

<div class="participant-content">
    <div class="video">
        <iframe src="{{ participant.video_url }}" scrolling="no"></iframe>
    </div>
    <div style="padding: 10px">
        <form id="vote-form-{{ participant.id }}" action="{% url 'voting:vote' %}" method="POST">
            {% csrf_token %}
            <input hidden name="participant-id" value="{{ participant.id }}" />
            <button type="submit" class="g-recaptcha"
                data-sitekey="6LeO5MYgAAAAAPgIWEGgve8v1m-uhehoU497FjxB"
                data-callback="onSubmit{{ participant.id }}" >{% translate "Votar" %}!</button>
        </form>
        <script type="text/javascript">
            function onSubmit{{ participant.id }}(token) {
                document.getElementById("vote-form-{{ participant.id }}").submit();
            }
        </script>
        <div class="votes">
            <span class="votes">{{ participant.votes }} {% translate "votos" %}</span>
        </div>
        <div class="name">
            <span class="name">{{ participant.name }}</span>
        </div>
        <details class="description">
            <summary>{% translate "Ver mais detalhes" %}</summary>
            <p>{{ participant.description|safe }}</p>
        </details>
    </div>
</div>

voting/templates/vote/participants.html
{% extends "contest/base.html" %}
{% load static %}
{% load i18n %}

{% block head %}
    <link href="{% static "vote/css/_participant.css" %}" rel="stylesheet" />
    <link href="{% static "vote/css/participants.css" %}" rel="stylesheet" />
{% endblock head %}

{% block content %}
    <div id="participants">
        {% for participant in participants %}
            <div class="participant">
                {% include "vote/_participant.html" %}
            </div>
        {% endfor %}
    </div>
{% endblock content %}